name: Aditya GitHub Actions

on: [push]

jobs:
  lab-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Action 1: Run Python aditya.py
    - name: Run Python Script
      run: python aditya.py

    # Action 2: Show author and date
    - name: Show Author and Date
      run: |
        echo "Author: Aditya"
        echo "Date:"
        date
