name: Aditya Workflow

on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Action 1 - Run Script
      run: |
        echo "Aditya Sharma - Running script!"
        echo 'print("Action 1 Success!")' > aditya.py
        echo 'print("file is modified!")' > aditya.py
        python aditya.py
        
    - name: Action 2 - Show info
      run: |
        echo "=== Aditya Sharma Info ==="
        pwd
        ls -la
        uname -a


